
import Foundation
import UIKit

struct Book{
    var title: String
    var author: String
    var price: Double
    var image: UIImage
    var description: String

}

let book1 = Book.init(title: "Beyond The Basic Stuff With Python", author: "Al Sweigart", price: 26.80, image: UIImage(named: "image1")!, description: "Welcome to Beyond the Basic Stuff with Python. More than a mere collection of advanced syntax and masterful tips for writing clean code, you'll learn how to advance your Python programming skills by using the command line and other professional tools like code formatters, type checkers, linters, and version control. Sweigart takes you through best practices for setting up your development environment, naming variables, and improving readability, then tackles documentation, organization and performance measurement, as well as object-oriented design and the Big-O algorithm analysis commonly used in coding interviews. The skills you learn will boost your ability to program--not just in Python but in any language.")

let book2 = Book.init(title: "clean Code", author: "Robert C. Martin", price: 21.25, image: UIImage(named: "image2")!, description: "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way.")

let book3 = Book.init(title: "Forge Your Future with Open Source", author: "VM (Vicky) Brasseur", price: 29.54, image: UIImage(named: "image3")!, description: "Free and open source is the foundation of software development, and it's built by people just like you. Discover the fundamental tenets that drive the movement. Take control of your career by selecting the right project to meet your professional goals. Master the language and avoid the pitfalls that typically ensnare new contributors. Join a community of like-minded people and change the world. Programmers, writers, designers, and everyone interested in software will make their mark through free and open source software contributions.")

let book4 = Book.init(title: "Grokking Algorithms", author: "Aditya Bhargava", price: 33.59, image: UIImage(named: "image4")!, description: "Grokking Algorithms is a fully illustrated, friendly guide that teaches you how to apply common algorithms to the practical problems you face every day as a programmer. You'll start with sorting and searching and, as you build up your skills in thinking algorithmically, you'll tackle more complex concerns such as data compression and artificial intelligence. Each carefully presented example includes helpful diagrams and fully annotated code samples in Python.")

let book5 = Book.init(title: "Introduction To Algorithms", author: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein", price: 119.22, image: UIImage(named: "image5")!, description: "Some books on algorithms are rigorous but incomplete; others cover masses of material but lack rigor. Introduction to Algorithms uniquely combines rigor and comprehensiveness. It covers a broad range of algorithms in depth, yet makes their design and analysis accessible to all levels of readers, with self-contained chapters and algorithms in pseudocode. Since the publication of the first edition, Introduction to Algorithms has become the leading algorithms text in universities worldwide as well as the standard reference for professionals. This fourth edition has been updated throughout.")

let book6 = Book.init(title: "Pro iPhone Development With Swift 5", author: "Wallace Wang", price: 44.99, image: UIImage(named: "image6")!, description: "If you’ve already learned the basics of Swift and iOS programming, it’s time to take your skills to the next level. In this follow up work to the best-selling Beginning iPhone Development with Swift, you’ll learn tips for organizing and debugging Swift code, using multi-threaded programming with Grand Central Dispatch, passing data between view controllers, and designing apps for multiple languages.")

let book7 = Book.init(title: "Python Crash Course", author: "Eric Matthes", price: 21.49, image: UIImage(named: "image7")!, description: "If you've been thinking about learning how to code or picking up Python, this internationally bestselling guide to the most popular programming language is your quickest, easiest way to get started and go! Even if you have no experience whatsoever, Python Crash Course, 2nd Edition, will have you writing programs, solving problems, building computer games, and creating data visualizations in no time.")

let book8 = Book.init(title: "The Clean Coder", author: "Robert C. Martin", price: 41.45, image: UIImage(named: "image8")!, description: "Programmers who endure and succeed amidst swirling uncertainty and nonstop pressure share a common attribute: They care deeply about the practice of creating software. They treat it as a craft. They are professionals.")

let book9 = Book.init(title: "The IOS Programming Big Nerd Ranch Guide", author: "Christian Keur ", price: 18.67, image: UIImage(named: "image9")!, description: "iOS Programming: The Big Nerd Ranch Guide leads you through the essential concepts, tools, and techniques for developing iOS applications. After completing this book, you will have the know-how and the confidence you need to tackle iOS projects of your own. Based on Big Nerd Ranch's popular iOS training and its well-tested materials and methodology, this bestselling guide teaches iOS concepts and coding in tandem. The result is instruction that is relevant and useful. Throughout the book, the authors explain what's important and share their insights into the larger context of the iOS platform. You get a real understanding of how iOS development works, the many features that are available, and when and where to apply what you've learned.")

let book10 = Book.init(title: "Think Like a Programmer", author: "V. Anton Spraul ", price: 20.49, image: UIImage(named: "image10")!, description: "The real challenge of programming isn't learning a language's syntax—it's learning to creatively solve problems so you can build something great. In this one-of-a-kind text, author V. Anton Spraul breaks down the ways that programmers solve problems and teaches you what other introductory books often ignore: how to Think Like a Programmer. Each chapter tackles a single programming concept, like classes, pointers, and recursion, and open-ended exercises throughout challenge you to apply your knowledge.")
